config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #create
  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'
  #read
  get '/tasks', to: 'tasks#index'
  get '/tasks/:id', to: 'tasks#show', as: 'task_to_show'
  #update
  get '/tasks/:id/edit', to:'tasks#edit'
  patch '/tasks/:id', to:'tasks#update'
  #delete
  delete '/tasks/:id', to:'tasks#destroy', as: 'task_to_delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new()
  end

  def create
    @task = Task.new(task_params)
    @task.save
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update
    redirect_to task_path(@task)
  end

  def destroy
    task_to_delete = Task.find(params[:id])
    task_to_delete.destroy
    redirect_to tasks_path
  end


  private
  def task_params
    params.require(:task).permit(:name, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<% form_for @task do |form| %>
  <%= form.text_field :name %>
  <%= form.text_field :completed %>
  <%= form.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>All tasks</h1>

<% @tasks.each do |task| %>
  <h3><%= task.name %></h3>
  <h2><%= task.completed %></h2>
  <%= link_to 'Delete task', task_to_delete_path(task), method: :delete %>
  <%= link_to 'Show the task', task_to_show_path(task) %>
<% end %>

<%= link_to 'Create a new task', tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_for @task do |form| %>
<%= form.text_field :name %>
<%= form.text_field :completed %>
<%= form.submit %>
<% end %>

app/views/tasks/show.html.erb
<h3><%= @task.name %></h3>
<h2><%= @task.completed %></h2>


<%= link_to 'Back to all tasks', tasks_path %>
<%= link_to 'Destroy this task', task_to_delete_path(@task), method: :delete %>